version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: 
    secure: MIcFLX1viOzK5VYXq4XSoy6zxoDYX9alPhMsqYyCwhA=
  DOCKER_PASS:
    secure: PyGoV+3PtIghP8om1bvyjg==
install:
  - ps: Get-ChildItem env:DOCKER_USER
  - ps: Get-ChildItem env:DOCKER_PASS
  - docker version

build_script:
  - docker build -t monamimani/msbuild .

test: off

#test_script:
#  - docker run monamimani/msbuild

deploy_script:
  - docker login --u= env:DOCKER_USER --p= env:DOCKER_PASS
  - docker push monamimani/msbuild