version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: 
    secure: ZSRDBZxEwolrrD6xli1Vtg==
  DOCKER_PASS:
    secure: PyGoV+3PtIghP8om1bvyjg==
install:
  - docker version

build_script:
  - docker build -t monamimani/msbuild .

test_script:
  - docker run monamimani/msbuild

deploy_script:
  - docker login -u env:DOCKER_USER -p env:DOCKER_PASS
  - docker push monamimani/msbuild
  - docker logout