version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: 
    secure: ZSRDBZxEwolrrD6xli1Vtg==
  DOCKER_PASS:
    secure: PyGoV+3PtIghP8om1bvyjg==
install:
  - ps: docker version

build_script:
 - ps: docker build -t -m 2GB monamimani/msbuild .

test_script:
  - docker run monamimani/msbuild

deploy_script:
 - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
 - ps: docker push monamimani/msbuild
 - ps: docker logout
