version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: 
    secure: ZSRDBZxEwolrrD6xli1Vtg==
  DOCKER_PASS:
    secure: PyGoV+3PtIghP8om1bvyjg==
install:
  - ps: docker version

build_script:
 - ps: docker build -m 2GB -t monamimani/msbuild .
 - docker inspect monamimani/msbuild
 - ps: $ImgVer = docker inspect -format "{{ index .Config.Labels 'version'}}" monamimani/msbuild
 - ps: docker tag monamimani/msbuild monamimani/msbuild:"$ImgVer"

test_script:
  - docker images
  - docker run monamimani/msbuild
  - git clone https://github.com/monamimani/helloworld.git build
  - cd build
  - ps: docker run -v "$(pwd):C:\SourceCode" monamimani/msbuild msbuild helloworld.sln /p:Configuration=Release
  

deploy_script:
 - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
 - ps: docker push monamimani/msbuild
 - ps: docker logout
